gauss-project/aurorafs

- cmd/internal/file/io.go
- pkg/encryption/store/decrypt_store.go
- pkg/file/joiner/joiner.go
- pkg/localstore/mode_get.go
- pkg/netstore/netstore.go
- pkg/node/node.go
- pkg/routetab/routetab.go
- pkg/routetab/service.go
- pkg/storage/mock/storer.go
- pkg/storage/store.go
- pkg/traversal/triedata.go
merge node boot and netstore fix retrival
> Netstore dev

- pkg/api/file.go
- pkg/api/pin_auroras.go
- pkg/api/pin_chunks.go
- pkg/api/pin_file.go
- pkg/api/router.go
- pkg/api/soc.go
- pkg/aurora/address.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/chunkpyramid.go
- pkg/chunkinfo/mock/chunkinfo.go
- pkg/debugapi/chunk.go
- pkg/debugapi/chunk_test.go
- pkg/jsonhttp/jsonhttp.go
- pkg/localstore/mode_has.go
- pkg/retrieval/retrieval_test.go
- pkg/storage/mock/storer.go
- pkg/storage/store.go
- pkg/traversal/triedata.go
> [update] Gc-pin optimization modification

- openapi/Aurora.yaml
- openapi/AuroraCommon.yaml
- openapi/AuroraDebug.yaml
- pkg/api/dirs.go
- pkg/api/file.go
- pkg/api/router.go
- pkg/aurora/address.go
- pkg/bitvector/bitvector.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/p2p/p2p.go
Modify api and api documentation.
> [update] Modify api and api documentation.

- pkg/api/bzz.go
- pkg/api/chunk.go
- pkg/api/dirs.go
- pkg/api/file.go
- pkg/api/pin_chunks.go
- pkg/api/router.go
- pkg/chunkinfo/chunkinfo.go
- pkg/localstore/mode_set.go
> Vicent dev0915

- pkg/chunkinfo/chunkinfodiscover.go
- pkg/debugapi/debugapi_test.go
- pkg/netstore/netstore_test.go
- pkg/retrieval/aco/aco.go
- pkg/retrieval/aco/aco_test.go
- pkg/retrieval/retrieval.go
- version.go
fix: aco algorithm problems.
fix: make error.
refactor: logger & version.
refactor: aco lock.
> fix: aco algorithm problems

- pkg/chunkinfo/chunkinfodiscover.go
- pkg/retrieval/retrieval.go
- pkg/shed/db.go
refactor: retrieval go discover neighbor nodes.
feat: leveldb options.
> refactor: retrieval go discover neighbor nodes.

- pkg/chunkinfo/message.go
- pkg/chunkinfo/timeouttrigger.go
> fix: chunkinfo lock.

- pkg/api/aurora.go
fix: wrong position of filesize and size display.
> fix: wrong position of filesize and size display.

- cmd/aurorafs/cmd/cmd.go
- pkg/bitvector/bitvector.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/message.go
- pkg/chunkinfo/queue.go
feat: create a list of files when getting a pyramid.
fix: queue use error for loop.
refactor: configuring cross-domain defaults.
> feat: create a list of files when getting a pyramid.

- openapi/AuroraCommon.yaml
- openapi/AuroraDebug.yaml
- pkg/aurora/address.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfosource_test.go
- pkg/chunkinfo/chunkpyramid.go
- pkg/chunkinfo/message.go
- pkg/chunkinfo/metrics.go
- pkg/chunkinfo/mock/chunkinfo.go
- pkg/debugapi/chunkinfo.go
- pkg/debugapi/router.go
- pkg/retrieval/retrieval.go
- version.go
* feat(chunkinfo):Add the persistent storage function of source information for file chuncks and pyramid to ChunkInfo
* fix(retrieval): Submit the source information of file chuncks to ChunkInfo
* feat(debugApi): Add the chunk/source open interfaces
* docs: update openapi
* docs: update version
> Feat: Add the source information of file chunks to ChunkInfo/DebugApi/Retrieval

- pkg/api/aurora.go
- pkg/chunkinfo/message.go
- pkg/chunkinfo/metrics.go
- pkg/retrieval/metrics.go
- pkg/retrieval/retrieval.go
* feat(retrieval):Add traffic counts
* feat(chunkinfo):Add traffic counts
> Feat:Add traffic counts to retrieval/chunkinfo

- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/retrieval/retrieval.go
fix(chunkinfo): overlays is nil.
refactor(retrieval): remove invalid code.
> fix(chunkinfo): overlays is nil.

- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/queue.go
fix(chunkinfo): unlocked release lock.
> fix(chunkinfo): unlocked release lock.

- openapi/AuroraCommon.yaml
- openapi/AuroraDebug.yaml
* fix:Restore the display of node NAT interception and public address
> Fix:Restore the display of node NAT interception and public address

- pkg/api/aurora.go
- pkg/api/dirs.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfosource_test.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/chunkpyramid.go
- pkg/chunkinfo/mock/chunkinfo.go
- pkg/localstore/gc.go
- pkg/localstore/gc_test.go
- pkg/localstore/localstore.go
- pkg/localstore/localstore_test.go
- pkg/localstore/migration_test.go
- pkg/node/node.go
- pkg/retrieval/retrieval.go
- pkg/statestore/mock/store.go
- version.go
fix(chunkinfo): deleting data before the download is complete results in data not being deleted cleanly.
fix(gc): remove delPyramid method.
feat(chunkinfo): remove delPyramid method.
feat(chunkinfo): mock chunkinfo.
fix(chunkinfo):source test cases.
fix(localstore): delete all chunk under root by chunkinfo.
docs: version number changed to 1.1.7.
> fix(chunkinfo): deleting data before the download is complete results in data not being deleted cleanly.

- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/chain.go
- pkg/api/router.go
- pkg/debugapi/account.go
- pkg/debugapi/debugapi.go
- pkg/debugapi/debugapi_test.go
- pkg/debugapi/router.go
- pkg/node/chain.go
- pkg/node/node.go
- pkg/settlement/chain/common/common.go
- pkg/settlement/chain/service.go
- version.go
feat:  add chain rpc api.
feat: version 1.2.1.
> feat: add chain rpc api.

- pkg/accounting/accounting.go
- pkg/api/traffic.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfosource_test.go
- pkg/chunkinfo/message.go
- pkg/settlement/traffic/traffic.go
* fix:  Fix the traffic cheques query api error
> fix:  Optimization of flow charging api

- pkg/settlement/traffic/traffic.go
* fix: bug repair of traffic calculation error
> fix:  BUG repair of traffic calculation error

- pkg/chunkinfo/chunkpyramid.go
- pkg/chunkinfo/message.go
> fix: same chunk not recorded.

- pkg/api/traffic.go
- pkg/retrieval/retrieval.go
- version.go
fix: add api error prompt.
fix: move the position of the Debit function of accounting.
feat: version upgraded to 1.2.2.
> fix: add api error prompt

- openapi/Aurora.yaml
- openapi/AuroraCommon.yaml
- pkg/accounting/accounting.go
- pkg/api/api.go
- pkg/api/aurora.go
- pkg/api/router.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/node/chain.go
- pkg/node/node.go
- pkg/settlement/chain/oracle/chainoracle.go
- pkg/settlement/chain/oracle/mock/oracle.go
- pkg/settlement/chain/oracle/oracle.go
- pkg/settlement/chain/service.go
* fix: Modify aurora API to increase the return of manifest
* feat: Add file upload registration API
> feat:  Add file upload registration API and optimize aurora API

- pkg/api/api.go
- pkg/api/aurora.go
- pkg/settlement/chain/oracle/chainoracle.go
- pkg/settlement/chain/oracle/mock/oracle.go
- pkg/settlement/chain/service.go
* fix: Optimize aurora interface to cache the requested information on the chain.
> fix:  Optimize aurora api interface

- pkg/accounting/accounting.go
- pkg/retrieval/retrieval.go
- pkg/settlement/traffic/traffic.go
* fix:Error repair of flow charging outstanding balance
> fix: Accounting bug fix

- openapi/Aurora.yaml
- pkg/api/aurora.go
- pkg/api/dirs.go
- pkg/chunkinfo/chunkinfo.go
- pkg/localstore/gc.go
* fix: Optimization of file deletion in download
> Fix: Optimization of file deletion in download

- pkg/settlement/pseudosettle/pseudosettle.go
- pkg/settlement/traffic/traffic.go
* fix:Error handling of receiving check display
> fix: Optimization of flow charging api interface

- mobile/export_test.go
- mobile/node.go
- mobile/options.go
* can set domain resolver by ResolverOptions
* can enable accounting by EnableFlowStat and FlowContract
> Feat: mobile node update

- pkg/accounting/accounting.go
- pkg/node/node.go
- pkg/retrieval/retrieval.go
- pkg/settlement/traffic/traffic.go
fix: accounting lock change & retrieve redundant code removal.
fix: modification of payment thresholds.
> fix: accounting lock change & retrieve redundant code removal.

- mobile/options.go
- pkg/accounting/accounting.go
- pkg/accounting/accounting_test.go
- pkg/api/api.go
- pkg/api/api_test.go
- pkg/api/aurora.go
- pkg/chunkinfo/chunkinfosource_test.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/mock/chunkinfo.go
- pkg/settlement/traffic/traffic.go
- pkg/settlement/traffic/traffic_test.go
refactor: code optimisation.
refactor: traffic code optimisation.
> refactor: code optimisation.

- pkg/api/traffic.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/chunkpyramid.go
- pkg/chunkinfo/message.go
- pkg/chunkinfo/queue.go
- pkg/chunkinfo/timeouttrigger.go
* fix: Optimization of chunkInfo lock
> fix: Optimization of chunkInfo lock

- pkg/accounting/accounting.go
- pkg/api/traffic.go
- pkg/bitvector/bitvector.go
- pkg/node/node.go
- pkg/settlement/traffic/traffic.go
refactor: code optimisation.
refactor: blacklisting time changed to 24 hours.
refactor: payment tolerance quadrupled.
Fix the error that relay nodes only have pyramids and cannot continue downloading.
> refactor: code optimisation. 

- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/chunkpyramid.go
- pkg/chunkinfo/message.go
refactor: reduce pyramid memory footprint.
fix: delete logic.
> refactor: reduce pyramid memory footprint.

- pkg/chunkinfo/chunkinfo.go
- pkg/retrieval/retrieval.go
> feat: develop download nodes.

- pkg/chunkinfo/api.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfotabneighbor.go
feat: provide websocket interface to chunkinfo.
> feat: provide websocket interface to chunkinfo.

- pkg/chunkinfo/api.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/multicast/kademlia.go
feat: add chunkinfo status change interface.
fix: multicast protocol version upgrade.
> feat: add chunkinfo status change interface.

- pkg/chunkinfo/chunkpyramid.go
> fix: pyramid chunk record.

- pkg/chunkinfo/api.go
- pkg/node/node.go
- pkg/settlement/pseudosettle/pseudosettle.go
- pkg/settlement/traffic/api.go
- pkg/settlement/traffic/traffic.go
feat: provide websocket interface to traffic.
fix: rebooting to get traffic problems.
> feat: provide websocket interface to traffic.

- pkg/api/traffic.go
- pkg/settlement/traffic/traffic.go
> feat: operation status.

- pkg/settlement/traffic/traffic.go
fix:  send check notification after cashing.
> fix:  send check notification after cashing.

- pkg/api/api.go
- pkg/node/node.go
- pkg/settlement/chain/oracle/api.go
- pkg/settlement/chain/oracle/chainoracle.go
- pkg/settlement/chain/service.go
feat: oracle module adds websocket interface.
> feat: oracle module adds websocket interface.

- pkg/chunkinfo/chunkpyramid.go
fix: pyramid data recording error.
> fix: pyramid data recording error.

- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkpyramid.go
- pkg/chunkinfo/message.go
- pkg/localstore/localstore.go
- pkg/netstore/netstore.go
- pkg/netstore/netstore_test.go
- pkg/node/node.go
fix: chunk data recording error.
> fix: chunk data recording error.

- pkg/chunkinfo/chunkpyramid.go
- pkg/netstore/netstore.go
fix: not in the record pyramid repeat chunk.
> fix: not in the record pyramid repeat chunk.

- pkg/accounting/accounting.go
- pkg/node/node.go
fix: accounting module to reduce lock.
> fix: accounting module to reduce lock.

- pkg/api/aurora.go
- pkg/aurora/paging.go
> fix: incorrect paging data.

- pkg/api/aurora.go
fix: limit the number of gorountine.
> fix: limit the number of gorountine

- pkg/settlement/chain/traffic/chaintraffic.go
fix: add contract function timeout time.
> fix: add contract function timeout time.

- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfotabneighbor.go
perf: log printing at initialization.
> perf: log printing at initialization.

- pkg/api/aurora.go
- pkg/api/router.go
perf: remove the aurora/list interface&redundant fields.
> perf: remove the aurora/list interface&redundant fields.

- pkg/settlement/traffic/traffic.go
perf: reduce the time cost by traffic init
> perf: reduce the time cost by traffic init

- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/settlement/chain/traffic/chaintraffic.go
- pkg/settlement/traffic/traffic.go
- pkg/settlement/traffic/trafficprotocol/trafficprotocol.go
perf: traffic lock.
perf: timeout time reduced to 2 seconds.
perf: pub/sub to support multiple channels.
> Perf traffic

- pkg/api/traffic.go
- pkg/settlement/chain/traffic/chaintraffic.go
- pkg/settlement/chain/transaction/transaction.go
> perf: traffic sort.

- pkg/api/chain.go
- pkg/api/router.go
- pkg/node/chain.go
- pkg/settlement/chain/common/common.go
- pkg/settlement/chain/oracle/chainoracle.go
- pkg/settlement/chain/service.go
- pkg/settlement/chain/traffic/chaintraffic.go
- pkg/settlement/chain/transaction/transaction.go
- pkg/settlement/traffic/cheque/cashout.go
- pkg/settlement/traffic/cheque/chequestore.go
- pkg/settlement/traffic/traffic.go
pref: synchronized execution chain transactions.
> pref: synchronized execution chain transactions.

- pkg/settlement/traffic/traffic.go
fix: data error due to chain connection failure.
> fix: data error due to chain connection failure.

- pkg/settlement/chain/traffic/mock/chaintraffic.go
- pkg/settlement/traffic/api.go
- pkg/settlement/traffic/traffic.go
> perf: support all listening.

- pkg/settlement/traffic/traffic.go
fix: not using recursion.
perf: using goto.
> fix: not using recursion.

- pkg/accounting/accounting.go
- pkg/api/aurora.go
- pkg/api/dirs_test.go
- pkg/file/loadsave/loadsave.go
- pkg/traversal/traversal.go
> fix: deadlock issues.

- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/retrieval/aco/aco.go
- pkg/retrieval/weight/weight.go
- pkg/retrieval/weight/weight_test.go
feat: weight randomization algorithm.
perf: not showing incomplete files after data loss.
> feat: weight randomization algorithm.

- pkg/chunkinfo/chunkpyramid.go
- pkg/settlement/chain/oracle/chainoracle.go
- pkg/topology/kademlia/kademlia.go
- version.go
perf: set timeout time.
fix: use the channel access func.
docs: version 1.3.5.
> perf: set timeout time.

- pkg/settlement/traffic/trafficprotocol/trafficprotocol.go
fix: add a judgment that is nil.
> fix: add a judgment that is nil.

- pkg/api/aurora.go
- pkg/chunkinfo/chunkinfo.go
- pkg/chunkinfo/chunkinfo_test.go
- pkg/chunkinfo/chunkinfodiscover.go
- pkg/chunkinfo/chunkinfosource.go
- pkg/chunkinfo/chunkinfotabneighbor.go
- pkg/chunkinfo/manifest.go
- pkg/node/node.go
- pkg/settlement/traffic/trafficprotocol/trafficprotocol.go
perf: manifest data in memory.
> perf: manifest data in memory.

- pkg/settlement/traffic/cheque/chequestore.go
- pkg/settlement/traffic/traffic.go
Reverts gauss-project/aurorafs#257
> Revert "perf:  perf traffic initialization and perf getting traffic info"
